package com.travelersdiary.models;

import java.util.Map;

/**
 * Created by itrifonov on 31.12.2015.
 */
public class UserData {
    private Map<String, Travel> travels; // Key = travelId = UUID.randomUUID().toString();
    private Map<String, DiaryNote> diary; // Key = timestamp
    private Map<String, TrackPoint> tracks; // Key = ID generated by firebase's method push()
    private Map<String, ReminderItem> reminder; // Key = ID generated by firebase's method push()
    private Map<String, Waypoint> waypoints; // Key = ID generated by firebase's method push()
    private Map<String, TrackPoint> track; // Key = ID generated by firebase's method push()

    public UserData() {
    }

    public UserData(Map<String, Travel> travels, Map<String, DiaryNote> diary,
                    Map<String, TrackPoint> tracks, Map<String, ReminderItem> reminder,
                    Map<String, Waypoint> waypoints, Map<String, TrackPoint> track) {
        this.travels = travels;
        this.diary = diary;
        this.tracks = tracks;
        this.reminder = reminder;
        this.waypoints = waypoints;
        this.track = track;
    }

    public Map<String, Travel> getTravels() {
        return travels;
    }

    public void setTravels(Map<String, Travel> travels) {
        this.travels = travels;
    }

    public Map<String, DiaryNote> getDiary() {
        return diary;
    }

    public void setDiary(Map<String, DiaryNote> diary) {
        this.diary = diary;
    }

    public Map<String, TrackPoint> getTracks() {
        return tracks;
    }

    public void setTracks(Map<String, TrackPoint> tracks) {
        this.tracks = tracks;
    }

    public Map<String, ReminderItem> getReminder() {
        return reminder;
    }

    public void setReminder(Map<String, ReminderItem> reminder) {
        this.reminder = reminder;
    }

    public Map<String, Waypoint> getWaypoints() {
        return waypoints;
    }

    public void setWaypoints(Map<String, Waypoint> waypoints) {
        this.waypoints = waypoints;
    }

    public Map<String, TrackPoint> getTrack() {
        return track;
    }

    public void setTrack(Map<String, TrackPoint> track) {
        this.track = track;
    }
}
